services:
  - type: web
    name: coaxial-backend
    runtime: docker
    repo: https://github.com/ramniks05/coaxial-backend
    branch: master
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/actuator/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DB_URL
        value: jdbc:postgresql://dpg-d3jsavnfte5s73822hf0-a.oregon-postgres.render.com:5432/coaxial
      - key: DB_USERNAME
        value: coaxial
      - key: DB_PASSWORD
        value: XGOxywCzJ9q4Px2hCThRmwCjRAXzBymz
      - key: JWT_EXPIRATION
        value: 86400000
      - key: JWT_REFRESH_EXPIRATION
        value: 604800000
      - key: LOG_FILE_PATH
        value: /var/log/coaxial/application.log
    autoDeploy: true

